classes.dir=bin
project.name=BindingValidationSample
project.name.lowercase=bindingvalidationsample
project.type=application
principalClass=com.example.validationsample.Application
customInfoPListContent=
embed.Local=true
embed.Network=true
embed.Project=true
embed.System=true
embed.User=true
webXML=false
component.wellFormedTemplateRequired=false
component.inlineBindingPrefix=$
component.inlineBindingSuffix=
